apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: {{ include "byol-tfe-platform.namespace" . }}
  labels:
    {{- include "byol-tfe-platform.labels" . | nindent 4 }}
data:
  ARM_CLIENT_ID: {{ .Values.armClientId | quote }}
  ARM_TENANT_ID: {{ .Values.armTenantId | quote }}
  ARM_SUBSCRIPTION_ID: {{ .Values.armSubscriptionId | quote }}
  ARM_USE_OIDC: {{ .Values.armUseOidc | quote }}
  ARM_USE_CLI: {{ .Values.armUseCli | quote }}
  {{- if .Values.vaultEnabled }}
  VAULT_ADDR: {{ .Values.vaultAddress | quote }}
  VAULT_AUTH_METHOD: {{ .Values.vaultAuthMethod | quote }}
  VAULT_ROLE: {{ .Values.vaultRole | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tfe-config
  namespace: {{ include "byol-tfe-platform.namespace" . }}
  labels:
    {{- include "byol-tfe-platform.labels" . | nindent 4 }}
data:
  TFE_HOSTNAME: {{ .Values.platformHostname | quote }}
  TFE_OPERATIONAL_MODE: "external"
  TFE_TLS_CERT_FILE: "/etc/ssl/private/terraform-enterprise/cert.pem"
  TFE_TLS_KEY_FILE: "/etc/ssl/private/terraform-enterprise/key.pem"
  TFE_TLS_CA_BUNDLE_FILE: "/etc/ssl/private/terraform-enterprise/bundle.pem"
  TFE_DATABASE_HOST: {{ .Values.databaseHost | quote }}
  TFE_DATABASE_NAME: {{ .Values.databaseName | quote }}
  TFE_DATABASE_USER: {{ .Values.databaseUser | quote }}
  TFE_DATABASE_PARAMETERS: {{ .Values.databaseParameters | quote }}
  TFE_REDIS_URL: {{ .Values.redisUrl | quote }}
  TFE_OBJECT_STORAGE_TYPE: "azure"
  TFE_OBJECT_STORAGE_AZURE_ACCOUNT_NAME: {{ .Values.objectStorageAccountName | quote }}
  TFE_OBJECT_STORAGE_AZURE_CONTAINER: {{ .Values.objectStorageContainer | quote }}
  TFE_RUN_PIPELINE_MODE: "external"
  TFE_HTTP_PORT: "8080"
  TFE_HTTPS_PORT: "8443"
  TFE_VAULT_ENABLED: {{ .Values.vaultEnabled | quote }}
  {{- if .Values.vaultEnabled }}
  TFE_VAULT_ADDRESS: {{ .Values.vaultAddress | quote }}
  TFE_VAULT_CLUSTER_ADDRESS: {{ .Values.vaultClusterAddress | quote }}
  TFE_VAULT_DISABLE_MLOCK: {{ .Values.tfeVaultDisableMlock | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tfe-agent-config
  namespace: {{ include "byol-tfe-platform.namespace" . }}
  labels:
    {{- include "byol-tfe-platform.labels" . | nindent 4 }}
data:
  TFC_ADDRESS: {{ include "byol-tfe-platform.agentTfcAddress" . | quote }}
  TFC_AGENT_LOG_LEVEL: {{ .Values.agentLogLevel | quote }}