apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.kubernetesPullSecretName }}
  namespace: {{ include "byol-tfe-platform.namespace" . }}
  labels:
    {{- include "byol-tfe-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecretsRefreshInterval | quote }}
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault
  target:
    name: {{ .Values.kubernetesPullSecretName }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{{ `{{ .dockerconfigjson }}` }}'
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: {{ .Values.keyVaultPullSecretName | quote }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.kubernetesTfeSecretName }}
  namespace: {{ include "byol-tfe-platform.namespace" . }}
  labels:
    {{- include "byol-tfe-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecretsRefreshInterval | quote }}
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault
  target:
    name: {{ .Values.kubernetesTfeSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.keyVaultTfeSecretName | quote }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.kubernetesTfeAgentSecretName }}
  namespace: {{ include "byol-tfe-platform.namespace" . }}
  labels:
    {{- include "byol-tfe-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecretsRefreshInterval | quote }}
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault
  target:
    name: {{ .Values.kubernetesTfeAgentSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.keyVaultTfeAgentSecretName | quote }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.kubernetesTlsSecretName }}
  namespace: {{ include "byol-tfe-platform.namespace" . }}
  labels:
    {{- include "byol-tfe-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecretsRefreshInterval | quote }}
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault
  target:
    name: {{ .Values.kubernetesTlsSecretName }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        tls.crt: '{{ `{{ .tlsCrt }}` }}'
        tls.key: '{{ `{{ .tlsKey }}` }}'
  data:
    - secretKey: tlsCrt
      remoteRef:
        key: {{ .Values.keyVaultTlsCrtSecretName | quote }}
    - secretKey: tlsKey
      remoteRef:
        key: {{ .Values.keyVaultTlsKeySecretName | quote }}