apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: {{ include "byol-tfe-platform.namespace" . }}
  labels:
    {{- include "byol-tfe-platform.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.keyVaultUrl | quote }}
      serviceAccountRef:
        name: azure-keyvault-reader