apiVersion: v1
kind: ServiceAccount
metadata:
  name: tfe
  namespace: {{ include "byol-tfe-platform.namespace" . }}
  labels:
    {{- include "byol-tfe-platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tfe-agent
  namespace: {{ include "byol-tfe-platform.namespace" . }}
  labels:
    {{- include "byol-tfe-platform.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.armClientId | quote }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-keyvault-reader
  namespace: {{ include "byol-tfe-platform.namespace" . }}
  labels:
    {{- include "byol-tfe-platform.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.keyVaultClientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.keyVaultTenantId | quote }}
automountServiceAccountToken: false