apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
automountServiceAccountToken: false