namespace: tfeplatform
createNamespace: true

platformHostname: tfe.example.corp
serviceType: LoadBalancer
serviceInternalLoadBalancer: false
tfeStorageSizeGi: 20Gi
tfeStorageClassName: ""

keyVaultUrl: https://example-keyvault.vault.azure.net
keyVaultClientId: 00000000-0000-0000-0000-000000000000
keyVaultTenantId: 00000000-0000-0000-0000-000000000000
externalSecretsRefreshInterval: 1h

armClientId: 00000000-0000-0000-0000-000000000000
armTenantId: 00000000-0000-0000-0000-000000000000
armSubscriptionId: 00000000-0000-0000-0000-000000000000
armUseOidc: true
armUseCli: false

databaseHost: postgres.example.corp:5432
databaseName: tfe
databaseUser: tfe
databaseParameters: sslmode=require

redisUrl: redis://redis.example.corp:6379
objectStorageAccountName: exampleaccount
objectStorageContainer: tfestate

agentTfcAddress: ""
agentLogLevel: info
agentImagePullPolicy: IfNotPresent

vaultEnabled: false
vaultAddress: https://vault.example.corp:8200
vaultClusterAddress: https://vault.example.corp:8201
vaultAuthMethod: kubernetes
vaultRole: tfe-agent
tfeVaultDisableMlock: true

tfeReplicaCount: 1
agentReplicaCount: 1

kubernetesPullSecretName: hc-pull-secret
kubernetesTfeSecretName: tfe-secrets
kubernetesTfeAgentSecretName: tfe-agent-secrets
kubernetesTlsSecretName: tfe-tls
keyVaultTfeSecretName: tfe-secrets
keyVaultTfeAgentSecretName: tfe-agent-secrets
keyVaultTlsCrtSecretName: tfe-tls-crt
keyVaultTlsKeySecretName: tfe-tls-key
keyVaultPullSecretName: hc-pull-secret

tfeResources:
  requests:
    memory: 3Gi
    cpu: 350m
  limits:
    memory: 4Gi
    cpu: 2000m

agentResources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

global:
  azure:
    images:
      tfe:
        registry: crest.azurecr.io
        image: terraform-enterprise
        tag: v202501-1
        digest: sha256:53a98c93d4f5e6655b439569d7fce717521e4e5655e3cf4ee107d0536fb47f0d
      tfeAgent:
        registry: crest.azurecr.io/hashicorp
        image: tfc-agent
        tag: 1.28.10
        digest: sha256:2a910a85203760d84de8da4a95d839599cb50253cfac1f4ed23a6bd94dd8f5f4
      tlsInit:
        registry: crest.azurecr.io/library
        image: busybox
        tag: 1.37.0
        digest: sha256:7a634b8e555c3f394551ae422325e7f9d9d1420e8ac7e8f7ac6ce311dca91b0d
