apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hc-pull-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault
  target:
    name: hc-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{{ .dockerconfigjson }}'
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: hc-pull-secret