apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://example-keyvault.vault.azure.net
      serviceAccountRef:
        name: azure-keyvault-reader