apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-keyvault-reader
  annotations:
    azure.workload.identity/client-id: 00000000-0000-0000-0000-000000000000
    azure.workload.identity/tenant-id: 00000000-0000-0000-0000-000000000000
automountServiceAccountToken: false