apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tfeplatform
resources:
  - serviceaccount.yaml
  - job.yaml
  - ../../integrations/azure-keyvault/jobs-config
configMapGenerator:
  - name: config-platform-config
    envs:
      - config/platform.env
  - name: config-pipeline-config
    envs:
      - config/job.env
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: pipeline-image
    newName: crest.azurecr.io/unified-iac-stack/pipeline-runner
    digest: sha256:1d8c8397c2e54136b68af13595dd35b91a7b3a38214c23ad42db7f003bca4dce
replacements:
  - source:
      kind: ConfigMap
      name: config-platform-config
      fieldPath: data.ARM_CLIENT_ID
    targets:
      - select:
          kind: ServiceAccount
          name: config-pipeline
        fieldPaths:
          - metadata.annotations.[azure.workload.identity/client-id]
        options:
          create: true