namespace: tfeplatform
createNamespace: true

platformHostname: tfe.example.corp
serviceType: LoadBalancer
serviceInternalLoadBalancer: false
tfeStorageSizeGi: 20Gi
tfeStorageClassName: managed-csi

keyVaultUrl: https://example-keyvault.vault.azure.net
keyVaultClientId: 11111111-1111-1111-1111-111111111111
keyVaultTenantId: 22222222-2222-2222-2222-222222222222
externalSecretsRefreshInterval: 1h

armClientId: 33333333-3333-3333-3333-333333333333
armTenantId: 22222222-2222-2222-2222-222222222222
armSubscriptionId: 44444444-4444-4444-4444-444444444444
armUseOidc: true
armUseCli: false

databaseHost: postgres.example.corp:5432
databaseName: tfe
databaseUser: tfe
databaseParameters: sslmode=require

redisUrl: redis://redis.example.corp:6379
objectStorageAccountName: exampleaccount
objectStorageContainer: tfestate

agentTfcAddress: https://tfe.example.corp
agentLogLevel: info
agentImagePullPolicy: IfNotPresent

vaultEnabled: false
vaultAddress: https://vault.example.corp:8200
vaultClusterAddress: https://vault.example.corp:8201
vaultAuthMethod: kubernetes
vaultRole: tfe-agent
tfeVaultDisableMlock: true

tfeReplicaCount: 1
agentReplicaCount: 1

kubernetesPullSecretName: hc-pull-secret
kubernetesTfeSecretName: tfe-secrets
kubernetesTfeAgentSecretName: tfe-agent-secrets
kubernetesTlsSecretName: tfe-tls
keyVaultTfeSecretName: tfe-secrets
keyVaultTfeAgentSecretName: tfe-agent-secrets
keyVaultTlsCrtSecretName: tfe-tls-crt
keyVaultTlsKeySecretName: tfe-tls-key
keyVaultPullSecretName: hc-pull-secret

tfeResources:
  requests:
    memory: 3Gi
    cpu: 350m
  limits:
    memory: 4Gi
    cpu: 2000m

agentResources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

global:
  azure:
    images:
      tfe:
        registry: crest.azurecr.io
        image: terraform-enterprise
        digest: sha256:53a98c93d4f5e6655b439569d7fce717521e4e5655e3cf4ee107d0536fb47f0d
      tfeAgent:
        registry: crest.azurecr.io/hashicorp
        image: tfc-agent
        digest: sha256:cec9c92f86f6f27d9fef9c6f44461e48994207a71f70cd21749dd54e9a395765
      tlsInit:
        registry: crest.azurecr.io/library
        image: busybox
        digest: sha256:92b1d1cae5f235812184415e63d9b24464116c58d3ba3c460b1eb0247f0f46e3
